# -*- coding: utf-8 -*-
"""finetune_nietzsche.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13us_mZpv5TdBoV9-Het0yjz96gN0ccor

# 니체 페르소나 챗봇 파인튜닝
- 모델: `unsloth/Qwen2.5-3B-Instruct`
- 데이터: `nietzsche_ko.json` (한국어 QA 437개)
"""

!pip install unsloth trl -q

from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-3B-Instruct",
    max_seq_length=2048,
    load_in_4bit=True,
)
print("모델 로딩 완료")

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    use_gradient_checkpointing=True,
)
print("LoRA 설정 완료")

"""## 데이터 로딩 및 포맷 변환"""

from google.colab import drive
drive.mount("/content/drive")

import json
from datasets import Dataset

data_path = "/content/drive/MyDrive/git/4-finetuning/이서진/data/nietzsche_ko.json"

with open(data_path, "r", encoding="utf-8") as f:
    raw_data = json.load(f)

print(f"로딩된 데이터 수: {len(raw_data)}개")
print(f"샘플: {raw_data[0]}")



"""

*   모든 데이터의 instruction이 동일하므로, 매번 포맷 인자로 넘기는 대신 시스템 프롬프트에 고정.

"""

EOS_TOKEN = tokenizer.eos_token

alpaca_prompt = """<|im_start|>system
당신은 독일 철학자 프리드리히 니체입니다.
반드시 한국어로 답하되, 니체의 문체로 말하세요.
<|im_end|>
<|im_start|>user
{input}
<|im_end|>
<|im_start|>assistant
{output}
"""

def format_instruction(example):
    return {
        "text": alpaca_prompt.format(
            input=example["input"],
            output=example["output"]
        ) + EOS_TOKEN
    }

dataset = Dataset.from_list(raw_data)
dataset = dataset.map(format_instruction)
print(f"포맷 변환 완료: {len(dataset)}개")
print(dataset[0]["text"])

"""## 파인튜닝 전 응답 확인"""

import warnings
warnings.filterwarnings("ignore")
import transformers
transformers.logging.set_verbosity_error()

FastLanguageModel.for_inference(model)

test_questions = [
    "신은 죽었다는 말이 무슨 의미인가요?",
    "어떻게 살아야 행복할 수 있나요?",
    "약자를 도와야 하지 않나요?",
    "인공지능의 시대에 인간은 어떤 의미를 가지나요?",
    "삶이 너무 힘듭니다. 어떻게 해야 하나요?"
]

def generate_response(question):
    prompt = alpaca_prompt.format(input=question, output="")
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model.generate(
        **inputs,
        max_new_tokens=256,
        temperature=0.7,
        do_sample=True,
    )
    # 입력 토큰 수만큼 제외하고 새로 생성된 부분만 디코딩
    input_length = inputs["input_ids"].shape[1]
    decoded = tokenizer.decode(outputs[0][input_length:], skip_special_tokens=True)
    return decoded.strip()

before_responses = {}
print("=== 파인튜닝 전 응답 ===")
for q in test_questions:
    resp = generate_response(q)
    before_responses[q] = resp
    print(f"Q: {q}")
    print(f"A: {resp}")
    print()

"""## 파인튜닝"""

from trl import SFTTrainer
from transformers import TrainingArguments

FastLanguageModel.for_training(model)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        num_train_epochs=3,
        learning_rate=2e-4,
        warmup_ratio=0.1,
        lr_scheduler_type="cosine",
        fp16=True,
        logging_steps=10,
        output_dir="outputs",
        save_strategy="no",
    ),
)

trainer.train()
print("파인튜닝 완료")

"""## 파인튜닝 후 응답 확인 및 비교"""

FastLanguageModel.for_inference(model)

print("=== 파인튜닝 전후 비교 ===")
for q in test_questions:
    after_resp = generate_response(q)
    print(f"Q: {q}")
    print(f"[Before] {before_responses[q]}")
    print(f"[After]  {after_resp}")
    print()

"""## 모델 저장"""

# 저장 경로 직접 수정
model_save_path = "/content/drive/MyDrive/git/4-finetuning/이서진/model/nietzsche-qwen2.5-3b"
model.save_pretrained(model_save_path)
tokenizer.save_pretrained(model_save_path)
print(f"모델 저장 완료: {model_save_path}")

